BEGIN;

CREATE TABLE IF NOT EXISTS f_effectif_snapshot (
    effectif_snapshot_key BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    snapshot_date_key INTEGER NOT NULL REFERENCES d_temps (date_key),
    personnel_key INTEGER NOT NULL REFERENCES d_personnel (personnel_key),
    service_key INTEGER NOT NULL REFERENCES d_service (service_key),
    gouvernorat_key INTEGER NOT NULL REFERENCES d_gouvernorat (gouvernorat_key),
    grade_key INTEGER NOT NULL REFERENCES d_grade (grade_key),
    etat_act_key INTEGER NOT NULL REFERENCES d_etat_act (etat_act_key),
    sexe_key INTEGER NOT NULL REFERENCES d_sexe (sexe_key),
    nb_agent INTEGER NOT NULL DEFAULT 1,
    age INTEGER,
    anciennete_jours INTEGER,
    cod_soc VARCHAR(50) NOT NULL,
    mat_pers VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_f_effectif_snapshot UNIQUE (snapshot_date_key, personnel_key)
);

CREATE INDEX IF NOT EXISTS idx_f_effectif_snapshot_date ON f_effectif_snapshot (snapshot_date_key);
CREATE INDEX IF NOT EXISTS idx_f_effectif_snapshot_personnel ON f_effectif_snapshot (personnel_key);

CREATE TABLE IF NOT EXISTS f_demande_conge (
    demande_conge_key BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date_demande_key INTEGER NOT NULL REFERENCES d_temps (date_key),
    date_debut_key INTEGER NOT NULL REFERENCES d_temps (date_key),
    date_fin_key INTEGER NOT NULL REFERENCES d_temps (date_key),
    personnel_key INTEGER NOT NULL REFERENCES d_personnel (personnel_key),
    service_key INTEGER NOT NULL REFERENCES d_service (service_key),
    motif_conge_key INTEGER NOT NULL REFERENCES d_motif_conge (motif_conge_key),
    statut_conge_key INTEGER NOT NULL REFERENCES d_statut_conge (statut_conge_key),
    nb_demande INTEGER NOT NULL DEFAULT 1,
    nbr_jours NUMERIC(12, 2),
    nbr_heure NUMERIC(12, 2),
    nbr_jours_cal NUMERIC(12, 2),
    cod_soc VARCHAR(50) NOT NULL,
    mat_pers VARCHAR(50) NOT NULL,
    num_dcng VARCHAR(100) NOT NULL,
    date_demande DATE,
    date_debut DATE,
    date_fin DATE,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_f_demande_conge UNIQUE (cod_soc, mat_pers, num_dcng)
);

CREATE INDEX IF NOT EXISTS idx_f_demande_conge_dates ON f_demande_conge (date_debut_key, date_fin_key);
CREATE INDEX IF NOT EXISTS idx_f_demande_conge_personnel ON f_demande_conge (personnel_key);

CREATE TABLE IF NOT EXISTS f_justificatif_conge (
    justificatif_conge_key BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date_justif_key INTEGER NOT NULL REFERENCES d_temps (date_key),
    personnel_key INTEGER NOT NULL REFERENCES d_personnel (personnel_key),
    service_key INTEGER NOT NULL REFERENCES d_service (service_key),
    motif_conge_key INTEGER NOT NULL REFERENCES d_motif_conge (motif_conge_key),
    nb_justificatif INTEGER NOT NULL DEFAULT 1,
    cod_soc VARCHAR(50) NOT NULL,
    mat_pers VARCHAR(50) NOT NULL,
    num_dcng VARCHAR(100) NOT NULL,
    justif_ref VARCHAR(100) NOT NULL,
    date_justif DATE,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_f_justif_conge UNIQUE (cod_soc, mat_pers, num_dcng, justif_ref)
);

CREATE INDEX IF NOT EXISTS idx_f_justif_conge_date ON f_justificatif_conge (date_justif_key);
CREATE INDEX IF NOT EXISTS idx_f_justif_conge_personnel ON f_justificatif_conge (personnel_key);

CREATE TABLE IF NOT EXISTS f_pointage (
    pointage_key BIGINT GENERATED BY DEFAULT AS IDENTITY,
    event_date DATE NOT NULL,
    date_key INTEGER NOT NULL REFERENCES d_temps (date_key),
    personnel_key INTEGER NOT NULL REFERENCES d_personnel (personnel_key),
    service_key INTEGER NOT NULL REFERENCES d_service (service_key),
    type_pointage_key INTEGER NOT NULL REFERENCES d_type_pointage (type_pointage_key),
    nb_pointage INTEGER NOT NULL DEFAULT 1,
    ret_min NUMERIC(12, 2),
    duree_tot NUMERIC(12, 2),
    cod_soc VARCHAR(50) NOT NULL,
    mat_pers VARCHAR(50) NOT NULL,
    typ_point VARCHAR(20) NOT NULL,
    row_hash VARCHAR(64) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_f_pointage PRIMARY KEY (pointage_key, event_date),
    CONSTRAINT uq_f_pointage_nk UNIQUE (cod_soc, mat_pers, event_date, typ_point, row_hash)
) PARTITION BY RANGE (event_date);

CREATE TABLE IF NOT EXISTS f_pointage_default PARTITION OF f_pointage DEFAULT;

CREATE INDEX IF NOT EXISTS idx_f_pointage_date_key ON f_pointage (date_key);
CREATE INDEX IF NOT EXISTS idx_f_pointage_personnel ON f_pointage (personnel_key);
CREATE INDEX IF NOT EXISTS idx_f_pointage_event_date ON f_pointage (event_date);

CREATE TABLE IF NOT EXISTS f_retard_journalier (
    retard_key BIGINT GENERATED BY DEFAULT AS IDENTITY,
    event_date DATE NOT NULL,
    date_key INTEGER NOT NULL REFERENCES d_temps (date_key),
    personnel_key INTEGER NOT NULL REFERENCES d_personnel (personnel_key),
    service_key INTEGER NOT NULL REFERENCES d_service (service_key),
    etat_retard_key INTEGER NOT NULL REFERENCES d_etat_retard (etat_retard_key),
    nb_retard INTEGER NOT NULL DEFAULT 1,
    duree_tot NUMERIC(12, 2),
    cod_soc VARCHAR(50) NOT NULL,
    mat_pers VARCHAR(50) NOT NULL,
    etat_retard VARCHAR(20) NOT NULL,
    row_hash VARCHAR(64) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_f_retard PRIMARY KEY (retard_key, event_date),
    CONSTRAINT uq_f_retard_nk UNIQUE (cod_soc, mat_pers, event_date, etat_retard, row_hash)
) PARTITION BY RANGE (event_date);

CREATE TABLE IF NOT EXISTS f_retard_default PARTITION OF f_retard_journalier DEFAULT;

CREATE INDEX IF NOT EXISTS idx_f_retard_date_key ON f_retard_journalier (date_key);
CREATE INDEX IF NOT EXISTS idx_f_retard_personnel ON f_retard_journalier (personnel_key);
CREATE INDEX IF NOT EXISTS idx_f_retard_event_date ON f_retard_journalier (event_date);

CREATE TABLE IF NOT EXISTS etl_watermark (
    pipeline_name VARCHAR(100) PRIMARY KEY,
    last_pointage_date DATE,
    last_retard_date DATE,
    last_success_at TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS etl_run_log (
    run_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pipeline_name VARCHAR(100) NOT NULL,
    status VARCHAR(20) NOT NULL,
    started_at TIMESTAMP NOT NULL,
    finished_at TIMESTAMP,
    rows_effectif BIGINT DEFAULT 0,
    rows_demande_conge BIGINT DEFAULT 0,
    rows_justif_conge BIGINT DEFAULT 0,
    rows_pointage BIGINT DEFAULT 0,
    rows_retard BIGINT DEFAULT 0,
    error_message TEXT
);

COMMIT;
