BEGIN;

CREATE TABLE IF NOT EXISTS d_temps (
    date_key INTEGER PRIMARY KEY,
    full_date DATE NOT NULL UNIQUE,
    year_num INTEGER NOT NULL,
    quarter_num INTEGER NOT NULL,
    month_num INTEGER NOT NULL,
    month_name VARCHAR(20) NOT NULL,
    week_num INTEGER NOT NULL,
    day_num INTEGER NOT NULL,
    day_name VARCHAR(20) NOT NULL,
    is_weekend BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS d_service (
    service_key INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_serv VARCHAR(50) NOT NULL UNIQUE,
    lib_serv VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS d_gouvernorat (
    gouvernorat_key INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_gouv VARCHAR(50) NOT NULL UNIQUE,
    lib_gouv VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS d_grade (
    grade_key INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_grad VARCHAR(50) NOT NULL UNIQUE,
    lib_grad VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS d_etat_act (
    etat_act_key INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    etat_act VARCHAR(20) NOT NULL UNIQUE,
    etat_act_desc VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS d_sexe (
    sexe_key INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sexe VARCHAR(10) NOT NULL UNIQUE,
    sexe_desc VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS d_motif_conge (
    motif_conge_key INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_m VARCHAR(20) NOT NULL UNIQUE,
    lib_motif VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS d_statut_conge (
    statut_conge_key INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status_code VARCHAR(100) NOT NULL UNIQUE,
    valid VARCHAR(10),
    etat_cng VARCHAR(20),
    nat_cng VARCHAR(20),
    statut_desc VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS d_type_pointage (
    type_pointage_key INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    typ_point VARCHAR(20) NOT NULL UNIQUE,
    type_pointage_desc VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS d_etat_retard (
    etat_retard_key INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    etat_retard VARCHAR(20) NOT NULL UNIQUE,
    etat_retard_desc VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS d_personnel (
    personnel_key INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_soc VARCHAR(50) NOT NULL,
    mat_pers VARCHAR(50) NOT NULL,
    full_name VARCHAR(255),
    pren_pers VARCHAR(255),
    nom_pers VARCHAR(255),
    cod_serv VARCHAR(50),
    cod_gouv VARCHAR(50),
    cod_grad VARCHAR(50),
    etat_act VARCHAR(20),
    sexe VARCHAR(10),
    birth_date DATE,
    hire_date DATE,
    is_active BOOLEAN,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_d_personnel_nk UNIQUE (cod_soc, mat_pers)
);

CREATE INDEX IF NOT EXISTS idx_d_personnel_serv ON d_personnel (cod_serv);
CREATE INDEX IF NOT EXISTS idx_d_personnel_gouv ON d_personnel (cod_gouv);
CREATE INDEX IF NOT EXISTS idx_d_personnel_grad ON d_personnel (cod_grad);
CREATE INDEX IF NOT EXISTS idx_d_personnel_etat ON d_personnel (etat_act);

INSERT INTO d_temps (
    date_key,
    full_date,
    year_num,
    quarter_num,
    month_num,
    month_name,
    week_num,
    day_num,
    day_name,
    is_weekend
)
VALUES (0, DATE '1900-01-01', 1900, 1, 1, 'Unknown', 1, 1, 'Unknown', FALSE)
ON CONFLICT (date_key) DO NOTHING;

INSERT INTO d_service (service_key, cod_serv, lib_serv)
VALUES (0, 'UNK', 'Unknown service')
ON CONFLICT (cod_serv) DO NOTHING;

INSERT INTO d_gouvernorat (gouvernorat_key, cod_gouv, lib_gouv)
VALUES (0, 'UNK', 'Unknown gouvernorat')
ON CONFLICT (cod_gouv) DO NOTHING;

INSERT INTO d_grade (grade_key, cod_grad, lib_grad)
VALUES (0, 'UNK', 'Unknown grade')
ON CONFLICT (cod_grad) DO NOTHING;

INSERT INTO d_etat_act (etat_act_key, etat_act, etat_act_desc)
VALUES (0, 'UNK', 'Unknown etat actif')
ON CONFLICT (etat_act) DO NOTHING;

INSERT INTO d_sexe (sexe_key, sexe, sexe_desc)
VALUES (0, 'UNK', 'Unknown sexe')
ON CONFLICT (sexe) DO NOTHING;

INSERT INTO d_motif_conge (motif_conge_key, code_m, lib_motif)
VALUES (0, 'UNK', 'Unknown motif conge')
ON CONFLICT (code_m) DO NOTHING;

INSERT INTO d_statut_conge (statut_conge_key, status_code, valid, etat_cng, nat_cng, statut_desc)
VALUES (0, 'UNK|UNK|UNK', 'UNK', 'UNK', 'UNK', 'Unknown statut conge')
ON CONFLICT (status_code) DO NOTHING;

INSERT INTO d_type_pointage (type_pointage_key, typ_point, type_pointage_desc)
VALUES (0, 'UNK', 'Unknown type pointage')
ON CONFLICT (typ_point) DO NOTHING;

INSERT INTO d_etat_retard (etat_retard_key, etat_retard, etat_retard_desc)
VALUES (0, 'UNK', 'Unknown etat retard')
ON CONFLICT (etat_retard) DO NOTHING;

INSERT INTO d_personnel (
    personnel_key,
    cod_soc,
    mat_pers,
    full_name,
    pren_pers,
    nom_pers,
    cod_serv,
    cod_gouv,
    cod_grad,
    etat_act,
    sexe,
    is_active
)
VALUES (0, 'UNK', 'UNK', 'Unknown personnel', 'Unknown', 'Unknown', 'UNK', 'UNK', 'UNK', 'UNK', 'UNK', FALSE)
ON CONFLICT (cod_soc, mat_pers) DO NOTHING;

COMMIT;
