--- fix personnel 
ALTER TABLE "PERSONNEL"
ADD CONSTRAINT "UK_PERSONNEL_MAT_PERS" UNIQUE ("MAT_PERS");



CREATE TABLE IF NOT EXISTS "DEMANDE_CORRECTION_INFO" (
    "ID" BIGSERIAL PRIMARY KEY,
    "MAT_PERS" VARCHAR(8) NOT NULL,
    "ATTRIBUT_CIBLE" VARCHAR(32) NOT NULL,
    "ANCIENNE_VALEUR" TEXT,
    "NOUVELLE_VALEUR" TEXT NOT NULL,
    "STATUT" VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    "DATE_DEMANDE" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "PIECE_JOINTE" BYTEA NOT NULL,
    CONSTRAINT "FK_DEM_CORR_PERSONNEL" FOREIGN KEY ("MAT_PERS") REFERENCES "PERSONNEL" ("MAT_PERS"),
    CONSTRAINT "CHK_DEM_CORR_MAT_PERS" CHECK ("MAT_PERS" ~ '^[0-9]{8}$'),
    CONSTRAINT "CHK_DEM_CORR_ATTRIBUT" CHECK ("ATTRIBUT_CIBLE" IN ('NOM', 'PRENOM', 'ADRESSE', 'TELEPHONE', 'EMAIL')),
    CONSTRAINT "CHK_DEM_CORR_STATUT" CHECK ("STATUT" IN ('PENDING', 'APPROVED', 'REJECTED')),
    CONSTRAINT "CHK_DEM_CORR_PJ_SIZE" CHECK (octet_length("PIECE_JOINTE") <= 2097152)
);

CREATE INDEX IF NOT EXISTS "IDX_DEM_CORR_STATUT_DATE"
    ON "DEMANDE_CORRECTION_INFO" ("STATUT", "DATE_DEMANDE" DESC);

CREATE INDEX IF NOT EXISTS "IDX_DEM_CORR_MAT_PERS"
    ON "DEMANDE_CORRECTION_INFO" ("MAT_PERS");


