-- Application-scoped schema generated from:
--   - JPA entities in server/src/main/java/com/sante/app/model
--   - repositories and projection SQL in server/src/main/java/com/sante/app/repository
--   - startup SQL initializers in server/src/main/resources/sql
-- Column types were checked against local PostgreSQL database grh_msp.
--
-- Scope note:
-- This file defines only tables/columns used by the application data layer.
-- For legacy tables, primary-key support columns are retained when they are part
-- of the local database primary key, even when the Java code does not read them.
--
-- Used table/column inventory:
-- ADR_PERS: COD_SOC, MAT_PERS, NUM_ADR, COD_DELEG, RUE, ADR_ELECTRONIQUE, TEL_PORT_PERS
-- AUTH_REFRESH_TOKEN: ID, TOKEN_HASH, MAT_PERS, EXPIRES_AT, REVOKED, REVOKED_AT, CREATED_AT
-- CHAT_ATTACHMENTS: ID, MESSAGE_ID, FILE_NAME, FILE_TYPE, FILE_SIZE, CONTENT
-- CHAT_MESSAGES: ID, SENDER_ID, RECIPIENT_ID, ROOM_ID, CONTENT, TIMESTAMP, TYPE, IS_READ
-- DELEGATION: COD_GOUV, COD_DELEG, LIB_DELEG
-- DEMANDE_CORRECTION_INFO: ID, MAT_PERS, ATTRIBUT_CIBLE, ANCIENNE_VALEUR, NOUVELLE_VALEUR,
--   STATUT, DATE_DEMANDE, PIECE_JOINTE, PIECE_JOINTE_NOM, PIECE_JOINTE_TYPE, PIECE_JOINTE_TAILLE
-- DEM_CNG: COD_SOC, MAT_PERS, NUM_DCNG, ANNEE_CNG, CODE_M, DAT_DCNG, DAT_DEBUT, DAT_FIN,
--   NBR_JOURS, NBR_JOURS_CAL, MOTIF_CNG, VALID, SOLD_CNG, MOTIF_REFUS
-- GOUVERNORAT: COD_GOUV, LIB_GOUV
-- GRADE: COD_CATEG, COD_CAT, COD_GRAD, LIB_GRAD
-- JOURS_FERIERS: COD_FERIE, REGIME_TRAV, LIB_FERIE, DAT_FERIER
-- LEAVE_ATTACHMENTS: ID, COD_SOC, MAT_PERS, NUM_DCNG, FILE_NAME, FILE_TYPE, FILE_SIZE, CONTENT, CREATED_AT
-- MOTIF_J: COD_M, TYP_CNG, LIB_MOT, SEXE, REQUIRES_ATTACHMENT, MAX_DAYS_PER_YEAR,
--   MAX_DAYS_PER_CAREER, DEDUCTS_FROM_BALANCE, IS_HALF_PAY
-- NOTIFICATIONS: id, MAT_PERS, MESSAGE, TYPE, IS_READ, CREATED_AT
-- OTP_MAIL_SETTINGS: ID, HOST, PORT, USERNAME, PASSWORD_ENCRYPTED, SMTP_AUTH, SECURITY_MODE,
--   STARTTLS_ENABLE, FROM_ADDRESS, CREATED_AT, UPDATED_AT
-- PERSONNEL: COD_SOC, MAT_PERS, NOM_PERS, PREN_PERS, SEXE, COD_SERV, COD_CATEG,
--   COD_CAT, COD_GRAD, POSTE_TRAV, COD_USER
-- POSTE_TRAV: COD_METIER, COD_POST, LIB_POST
-- SERVICE: COD_SOC, COD_SERV, SER_COD_SERV, LIB_SERV
-- SOCIETE: COD_SOC, LIB_SOC

CREATE SEQUENCE IF NOT EXISTS "AUTH_REFRESH_TOKEN_ID_seq" AS BIGINT START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS "CHAT_ATTACHMENTS_ID_seq" AS BIGINT START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS "CHAT_MESSAGES_ID_seq" AS BIGINT START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS "DEMANDE_CORRECTION_INFO_ID_seq" AS BIGINT START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS "LEAVE_ATTACHMENTS_ID_seq" AS BIGINT START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS "NOTIFICATIONS_id_seq" AS BIGINT START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS "GOUVERNORAT" (
    "COD_GOUV" VARCHAR(4) NOT NULL,
    "LIB_GOUV" VARCHAR(40) NOT NULL,
    CONSTRAINT "pk_gouvernorat" PRIMARY KEY ("COD_GOUV")
);

CREATE TABLE IF NOT EXISTS "SOCIETE" (
    "COD_SOC" VARCHAR(255) NOT NULL,
    "LIB_SOC" VARCHAR(255) NOT NULL,
    CONSTRAINT "pk_societe" PRIMARY KEY ("COD_SOC")
);

CREATE TABLE IF NOT EXISTS "DELEGATION" (
    "COD_GOUV" VARCHAR(4) NOT NULL,
    "COD_DELEG" VARCHAR(4) NOT NULL,
    "LIB_DELEG" VARCHAR(60) NOT NULL,
    CONSTRAINT "pk_delegation" PRIMARY KEY ("COD_DELEG"),
    CONSTRAINT "fk_deleg_gouv" FOREIGN KEY ("COD_GOUV") REFERENCES "GOUVERNORAT" ("COD_GOUV") DEFERRABLE
);

CREATE TABLE IF NOT EXISTS "SERVICE" (
    "COD_SOC" VARCHAR(4) NOT NULL,
    "COD_SERV" VARCHAR(10) NOT NULL,
    "SER_COD_SERV" VARCHAR(10),
    "LIB_SERV" VARCHAR(120) NOT NULL,
    CONSTRAINT "pk_service" PRIMARY KEY ("COD_SOC", "COD_SERV")
);

CREATE TABLE IF NOT EXISTS "POSTE_TRAV" (
    "COD_METIER" VARCHAR(4) NOT NULL,
    "COD_POST" VARCHAR(15) NOT NULL,
    "LIB_POST" VARCHAR(200),
    CONSTRAINT "pk_poste_trav" PRIMARY KEY ("COD_POST")
);

CREATE TABLE IF NOT EXISTS "GRADE" (
    "COD_CATEG" VARCHAR(4) NOT NULL,
    "COD_CAT" VARCHAR(4) NOT NULL,
    "COD_GRAD" VARCHAR(4) NOT NULL,
    "LIB_GRAD" VARCHAR(60),
    CONSTRAINT "pk_grade" PRIMARY KEY ("COD_CATEG", "COD_CAT", "COD_GRAD")
);

CREATE TABLE IF NOT EXISTS "PERSONNEL" (
    "COD_SOC" VARCHAR(255) NOT NULL,
    "MAT_PERS" VARCHAR(255) NOT NULL,
    "NOM_PERS" VARCHAR(255),
    "PREN_PERS" VARCHAR(255),
    "SEXE" VARCHAR(1),
    "COD_SERV" VARCHAR(10),
    "COD_CATEG" VARCHAR(4),
    "COD_CAT" VARCHAR(4),
    "COD_GRAD" VARCHAR(4),
    "POSTE_TRAV" VARCHAR(15),
    "COD_USER" VARCHAR(255),
    CONSTRAINT "pk_personnel" PRIMARY KEY ("COD_SOC", "MAT_PERS"),
    CONSTRAINT "UK_PERSONNEL_MAT_PERS" UNIQUE ("MAT_PERS"),
    CONSTRAINT "ck_personne_sexe" CHECK (("SEXE" IS NULL) OR ("SEXE" IN ('M', 'F'))),
    CONSTRAINT "fk_societe_personnel" FOREIGN KEY ("COD_SOC") REFERENCES "SOCIETE" ("COD_SOC"),
    CONSTRAINT "fk_personnel_prm_organigramme" FOREIGN KEY ("COD_SOC", "COD_SERV") REFERENCES "SERVICE" ("COD_SOC", "COD_SERV"),
    CONSTRAINT "fk_personnel_poste_trav" FOREIGN KEY ("POSTE_TRAV") REFERENCES "POSTE_TRAV" ("COD_POST"),
    CONSTRAINT "fk_personnel_grade" FOREIGN KEY ("COD_CATEG", "COD_CAT", "COD_GRAD") REFERENCES "GRADE" ("COD_CATEG", "COD_CAT", "COD_GRAD")
);

CREATE TABLE IF NOT EXISTS "ADR_PERS" (
    "COD_SOC" VARCHAR(4) NOT NULL,
    "MAT_PERS" VARCHAR(255) NOT NULL,
    "NUM_ADR" INTEGER NOT NULL,
    "COD_DELEG" VARCHAR(4),
    "RUE" VARCHAR(100),
    "ADR_ELECTRONIQUE" VARCHAR(255),
    "TEL_PORT_PERS" VARCHAR(255),
    CONSTRAINT "pk_adr_pers" PRIMARY KEY ("COD_SOC", "MAT_PERS", "NUM_ADR"),
    CONSTRAINT "fk_adr_societe" FOREIGN KEY ("COD_SOC") REFERENCES "SOCIETE" ("COD_SOC"),
    CONSTRAINT "fk_adr_delegation" FOREIGN KEY ("COD_DELEG") REFERENCES "DELEGATION" ("COD_DELEG")
);

CREATE TABLE IF NOT EXISTS "MOTIF_J" (
    "COD_M" VARCHAR(4) NOT NULL,
    "TYP_CNG" VARCHAR(4),
    "LIB_MOT" VARCHAR(60),
    "SEXE" VARCHAR(1),
    "REQUIRES_ATTACHMENT" BOOLEAN DEFAULT FALSE,
    "MAX_DAYS_PER_YEAR" INTEGER,
    "MAX_DAYS_PER_CAREER" INTEGER,
    "DEDUCTS_FROM_BALANCE" BOOLEAN DEFAULT FALSE,
    "IS_HALF_PAY" BOOLEAN DEFAULT FALSE,
    CONSTRAINT "pk_motif_j" PRIMARY KEY ("COD_M")
);

CREATE TABLE IF NOT EXISTS "DEM_CNG" (
    "COD_SOC" VARCHAR(4) NOT NULL,
    "MAT_PERS" VARCHAR(10) NOT NULL,
    "NUM_DCNG" INTEGER NOT NULL,
    "ANNEE_CNG" INTEGER,
    "CODE_M" VARCHAR(4),
    "DAT_DCNG" DATE NOT NULL,
    "DAT_DEBUT" DATE NOT NULL,
    "DAT_FIN" DATE NOT NULL,
    "NBR_JOURS" NUMERIC(7, 3),
    "NBR_JOURS_CAL" NUMERIC(7, 3),
    "MOTIF_CNG" VARCHAR(1000),
    "VALID" VARCHAR(1),
    "SOLD_CNG" NUMERIC(7, 3),
    "MOTIF_REFUS" VARCHAR(1000),
    CONSTRAINT "pk_dem_cng" PRIMARY KEY ("COD_SOC", "MAT_PERS", "NUM_DCNG"),
    CONSTRAINT "fk_dem_cng_motif_j" FOREIGN KEY ("CODE_M") REFERENCES "MOTIF_J" ("COD_M"),
    CONSTRAINT "fk_dem_cng_personnel" FOREIGN KEY ("COD_SOC", "MAT_PERS") REFERENCES "PERSONNEL" ("COD_SOC", "MAT_PERS")
);

CREATE TABLE IF NOT EXISTS "JOURS_FERIERS" (
    "COD_FERIE" VARCHAR(255) NOT NULL,
    "REGIME_TRAV" VARCHAR(1) NOT NULL,
    "LIB_FERIE" VARCHAR(255),
    "DAT_FERIER" VARCHAR(255),
    CONSTRAINT "pk_jours_feriers" PRIMARY KEY ("COD_FERIE", "REGIME_TRAV")
);

CREATE TABLE IF NOT EXISTS "LEAVE_ATTACHMENTS" (
    "ID" BIGINT NOT NULL DEFAULT nextval('"LEAVE_ATTACHMENTS_ID_seq"'::regclass),
    "COD_SOC" VARCHAR(4) NOT NULL,
    "MAT_PERS" VARCHAR(10) NOT NULL,
    "NUM_DCNG" INTEGER NOT NULL,
    "FILE_NAME" VARCHAR(255) NOT NULL,
    "FILE_TYPE" VARCHAR(255) NOT NULL,
    "FILE_SIZE" BIGINT NOT NULL,
    "CONTENT" BYTEA NOT NULL,
    "CREATED_AT" TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT "LEAVE_ATTACHMENTS_pkey" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "DEMANDE_CORRECTION_INFO" (
    "ID" BIGINT NOT NULL DEFAULT nextval('"DEMANDE_CORRECTION_INFO_ID_seq"'::regclass),
    "MAT_PERS" VARCHAR(8) NOT NULL,
    "ATTRIBUT_CIBLE" VARCHAR(32) NOT NULL,
    "ANCIENNE_VALEUR" VARCHAR(255),
    "NOUVELLE_VALEUR" VARCHAR(255) NOT NULL,
    "STATUT" VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    "DATE_DEMANDE" TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "PIECE_JOINTE" BYTEA,
    "PIECE_JOINTE_NOM" VARCHAR(255),
    "PIECE_JOINTE_TAILLE" BIGINT,
    "PIECE_JOINTE_TYPE" VARCHAR(255),
    CONSTRAINT "DEMANDE_CORRECTION_INFO_pkey" PRIMARY KEY ("ID"),
    CONSTRAINT "FK_DEM_CORR_PERSONNEL" FOREIGN KEY ("MAT_PERS") REFERENCES "PERSONNEL" ("MAT_PERS"),
    CONSTRAINT "CHK_DEM_CORR_MAT_PERS" CHECK (("MAT_PERS")::text ~ '^[0-9]{8}$'::text),
    CONSTRAINT "CHK_DEM_CORR_ATTRIBUT" CHECK ("ATTRIBUT_CIBLE" IN ('NOM', 'PRENOM', 'ADRESSE', 'TELEPHONE', 'EMAIL')),
    CONSTRAINT "CHK_DEM_CORR_STATUT" CHECK ("STATUT" IN ('PENDING', 'APPROVED', 'REJECTED')),
    CONSTRAINT "CHK_DEM_CORR_PJ_SIZE" CHECK (octet_length("PIECE_JOINTE") <= 2097152)
);

-- Local grh_msp has sequence AUTH_REFRESH_TOKEN_ID_seq, but the column default
-- was not attached at inspection time. The default below keeps inserts working
-- for the Java @GeneratedValue(strategy = IDENTITY) mapping.
CREATE TABLE IF NOT EXISTS "AUTH_REFRESH_TOKEN" (
    "ID" BIGINT NOT NULL DEFAULT nextval('"AUTH_REFRESH_TOKEN_ID_seq"'::regclass),
    "CREATED_AT" TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    "EXPIRES_AT" TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    "MAT_PERS" VARCHAR(64) NOT NULL,
    "REVOKED" BOOLEAN NOT NULL,
    "REVOKED_AT" TIMESTAMP WITHOUT TIME ZONE,
    "TOKEN_HASH" VARCHAR(128) NOT NULL,
    CONSTRAINT "AUTH_REFRESH_TOKEN_pkey" PRIMARY KEY ("ID"),
    CONSTRAINT "UKhuobpn80tp7as17rfk5adtatp" UNIQUE ("TOKEN_HASH")
);

CREATE TABLE IF NOT EXISTS "OTP_MAIL_SETTINGS" (
    "ID" BIGINT NOT NULL,
    "CREATED_AT" TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    "FROM_ADDRESS" VARCHAR(255),
    "HOST" VARCHAR(255) NOT NULL,
    "PASSWORD_ENCRYPTED" VARCHAR(2048),
    "PORT" INTEGER NOT NULL,
    "SMTP_AUTH" BOOLEAN NOT NULL,
    "STARTTLS_ENABLE" BOOLEAN NOT NULL,
    "UPDATED_AT" TIMESTAMP WITHOUT TIME ZONE,
    "USERNAME" VARCHAR(255),
    "SECURITY_MODE" VARCHAR(20) NOT NULL,
    CONSTRAINT "OTP_MAIL_SETTINGS_pkey" PRIMARY KEY ("ID"),
    CONSTRAINT "OTP_MAIL_SETTINGS_SECURITY_MODE_check" CHECK ("SECURITY_MODE" IN ('NONE', 'STARTTLS', 'SSL_TLS'))
);

CREATE TABLE IF NOT EXISTS "CHAT_MESSAGES" (
    "ID" BIGINT NOT NULL DEFAULT nextval('"CHAT_MESSAGES_ID_seq"'::regclass),
    "SENDER_ID" VARCHAR(255) NOT NULL,
    "RECIPIENT_ID" VARCHAR(255),
    "ROOM_ID" VARCHAR(255),
    "CONTENT" TEXT,
    "TIMESTAMP" TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    "TYPE" VARCHAR(255) NOT NULL,
    "IS_READ" BOOLEAN NOT NULL,
    CONSTRAINT "CHAT_MESSAGES_pkey" PRIMARY KEY ("ID"),
    CONSTRAINT "FK_CHAT_MESSAGES_SENDER" FOREIGN KEY ("SENDER_ID") REFERENCES "PERSONNEL" ("MAT_PERS"),
    CONSTRAINT "FK_CHAT_MESSAGES_RECIPIENT" FOREIGN KEY ("RECIPIENT_ID") REFERENCES "PERSONNEL" ("MAT_PERS")
);

CREATE TABLE IF NOT EXISTS "CHAT_ATTACHMENTS" (
    "ID" BIGINT NOT NULL DEFAULT nextval('"CHAT_ATTACHMENTS_ID_seq"'::regclass),
    "MESSAGE_ID" BIGINT,
    "FILE_NAME" VARCHAR(255) NOT NULL,
    "FILE_TYPE" VARCHAR(255) NOT NULL,
    "FILE_SIZE" BIGINT,
    "CONTENT" BYTEA NOT NULL,
    CONSTRAINT "CHAT_ATTACHMENTS_pkey" PRIMARY KEY ("ID"),
    CONSTRAINT "FK_CHAT_ATTACHMENTS_MESSAGE" FOREIGN KEY ("MESSAGE_ID") REFERENCES "CHAT_MESSAGES" ("ID") ON DELETE CASCADE
);

ALTER TABLE "CHAT_ATTACHMENTS"
    ADD COLUMN IF NOT EXISTS "CONTENT" BYTEA;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = current_schema()
          AND table_name = 'CHAT_ATTACHMENTS'
          AND column_name = 'FILE_PATH'
    ) THEN
        ALTER TABLE "CHAT_ATTACHMENTS" ALTER COLUMN "FILE_PATH" DROP NOT NULL;
    END IF;

    UPDATE "CHAT_ATTACHMENTS"
    SET "CONTENT" = decode('', 'hex')
    WHERE "CONTENT" IS NULL;

    ALTER TABLE "CHAT_ATTACHMENTS" ALTER COLUMN "CONTENT" SET NOT NULL;
END $$;

CREATE TABLE IF NOT EXISTS "NOTIFICATIONS" (
    "id" BIGINT NOT NULL DEFAULT nextval('"NOTIFICATIONS_id_seq"'::regclass),
    "MAT_PERS" VARCHAR(10) NOT NULL,
    "MESSAGE" VARCHAR(500) NOT NULL,
    "TYPE" VARCHAR(255) NOT NULL,
    "IS_READ" BOOLEAN NOT NULL DEFAULT FALSE,
    "CREATED_AT" TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "NOTIFICATIONS_pkey" PRIMARY KEY ("id")
);

ALTER SEQUENCE "AUTH_REFRESH_TOKEN_ID_seq" OWNED BY "AUTH_REFRESH_TOKEN"."ID";
ALTER SEQUENCE "CHAT_ATTACHMENTS_ID_seq" OWNED BY "CHAT_ATTACHMENTS"."ID";
ALTER SEQUENCE "CHAT_MESSAGES_ID_seq" OWNED BY "CHAT_MESSAGES"."ID";
ALTER SEQUENCE "DEMANDE_CORRECTION_INFO_ID_seq" OWNED BY "DEMANDE_CORRECTION_INFO"."ID";
ALTER SEQUENCE "LEAVE_ATTACHMENTS_ID_seq" OWNED BY "LEAVE_ATTACHMENTS"."ID";
ALTER SEQUENCE "NOTIFICATIONS_id_seq" OWNED BY "NOTIFICATIONS"."id";

CREATE INDEX IF NOT EXISTS "IDX_LEAVE_ATTACHMENTS_DEM_CNG"
    ON "LEAVE_ATTACHMENTS" ("COD_SOC", "MAT_PERS", "NUM_DCNG");

CREATE INDEX IF NOT EXISTS "IDX_DEM_CORR_MAT_PERS"
    ON "DEMANDE_CORRECTION_INFO" ("MAT_PERS");

CREATE INDEX IF NOT EXISTS "IDX_DEM_CORR_STATUT_DATE"
    ON "DEMANDE_CORRECTION_INFO" ("STATUT", "DATE_DEMANDE" DESC);

CREATE INDEX IF NOT EXISTS "IDX_CHAT_MESSAGES_SENDER"
    ON "CHAT_MESSAGES" ("SENDER_ID");

CREATE INDEX IF NOT EXISTS "IDX_CHAT_MESSAGES_RECIPIENT"
    ON "CHAT_MESSAGES" ("RECIPIENT_ID");

CREATE INDEX IF NOT EXISTS "IDX_CHAT_MESSAGES_ROOM"
    ON "CHAT_MESSAGES" ("ROOM_ID");

CREATE INDEX IF NOT EXISTS "IDX_CHAT_ATTACHMENTS_MESSAGE"
    ON "CHAT_ATTACHMENTS" ("MESSAGE_ID");

CREATE INDEX IF NOT EXISTS "idx_notifications_mat_pers"
    ON "NOTIFICATIONS" ("MAT_PERS");

CREATE INDEX IF NOT EXISTS "idx_notifications_mat_pers_unread"
    ON "NOTIFICATIONS" ("MAT_PERS")
    WHERE "IS_READ" = FALSE;
