ALTER TABLE "DEMANDE_CORRECTION_INFO"
    ADD COLUMN IF NOT EXISTS "PIECE_JOINTE_NOM" varchar(255),
    ADD COLUMN IF NOT EXISTS "PIECE_JOINTE_TYPE" varchar(255),
    ADD COLUMN IF NOT EXISTS "PIECE_JOINTE_TAILLE" bigint;
