ALTER TABLE "MOTIF_J"
    ADD COLUMN IF NOT EXISTS "REQUIRES_ATTACHMENT" boolean DEFAULT false,
    ADD COLUMN IF NOT EXISTS "MAX_DAYS_PER_YEAR" integer,
    ADD COLUMN IF NOT EXISTS "MAX_DAYS_PER_CAREER" integer,
    ADD COLUMN IF NOT EXISTS "DEDUCTS_FROM_BALANCE" boolean DEFAULT false,
    ADD COLUMN IF NOT EXISTS "IS_HALF_PAY" boolean DEFAULT false;

CREATE TABLE IF NOT EXISTS "LEAVE_ATTACHMENTS" (
    "ID" bigserial PRIMARY KEY,
    "COD_SOC" varchar(4) NOT NULL,
    "MAT_PERS" varchar(10) NOT NULL,
    "NUM_DCNG" integer NOT NULL,
    "FILE_NAME" varchar(255) NOT NULL,
    "FILE_TYPE" varchar(255) NOT NULL,
    "FILE_SIZE" bigint NOT NULL,
    "CONTENT" bytea NOT NULL,
    "CREATED_AT" timestamp NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS "IDX_LEAVE_ATTACHMENTS_DEM_CNG"
    ON "LEAVE_ATTACHMENTS" ("COD_SOC", "MAT_PERS", "NUM_DCNG");

UPDATE "MOTIF_J" SET "SEXE" = 'F' WHERE "COD_M" = '04';
UPDATE "MOTIF_J" SET "SEXE" = 'M' WHERE "COD_M" = '12';

INSERT INTO "MOTIF_J" ("COD_M", "TYP_CNG", "LIB_MOT", "SEXE", "REQUIRES_ATTACHMENT", "MAX_DAYS_PER_YEAR", "DEDUCTS_FROM_BALANCE", "IS_HALF_PAY")
VALUES ('05', '02', U&'Cong\00E9 postnatal', 'F', false, 120, false, true)
ON CONFLICT ("COD_M") DO UPDATE SET
    "TYP_CNG" = COALESCE("MOTIF_J"."TYP_CNG", EXCLUDED."TYP_CNG"),
    "LIB_MOT" = COALESCE("MOTIF_J"."LIB_MOT", EXCLUDED."LIB_MOT"),
    "SEXE" = EXCLUDED."SEXE",
    "REQUIRES_ATTACHMENT" = EXCLUDED."REQUIRES_ATTACHMENT",
    "MAX_DAYS_PER_YEAR" = EXCLUDED."MAX_DAYS_PER_YEAR",
    "DEDUCTS_FROM_BALANCE" = EXCLUDED."DEDUCTS_FROM_BALANCE",
    "IS_HALF_PAY" = EXCLUDED."IS_HALF_PAY";
